
function ShopItem({ name, price, src }) {
    return (
        <div className="cursor-pointer transition-colors overflow-hidden ">
            <div className="w-full flex items-center justify-center aspect-square">
                <img src={src} alt="" />
            </div>
            <div className="px-1 py-2">
                <p className="text-sm text-white mt-0.5">{name}</p>
                <p className="text-[12px] text-cool-gray mt-0.5">{price}</p>
            </div>
        </div>
    );
}

export default function Shop() {
    // Placeholder text, generated by AI
    const items = [
        { name: "Electromagnetism Field Lines Poster", price: "₹2420", src: "./tshirt.jpg" },
        { name: "MF Logo Heavyweight Tee",             price: "₹1600", src: "./cap.jpg" },
        { name: "Science Lab Notebook, 200 pages",     price: "₹5200", src: "./shirt2.jpg" },
        { name: "Magnetic Desk Toy Kit",               price: "₹1200", src: "./cup.jpg" },
        { name: "Enamel Pin, Maxwell's Equations",     price: "₹1680",  src: "./bag.jpg" },
        { name: "MF Hoodie, Limited Edition",          price: "₹1770", src: "./shirt3.jpg" },
    ];

    return (
        <div className="px-3 pt-6 pb-2">
            <div className="grid grid-cols-2 gap-x-3 gap-y-6">
                {items.map(item => 
                    <ShopItem key={item.name} {...item} />
                )}
            </div>
        </div>
    );
}