import ShopCard from "../../components/Cards/ShopCard";

export default function Shop() {
    // Placeholder text, generated by AI
    const items = [
        { name: "Electromagnetism Field Lines Poster", price: "₹2420", src: "./tshirt.jpg" },
        { name: "MF Logo Heavyweight Tee", price: "₹1600", src: "./cap.jpg" },
        { name: "Science Lab Notebook, 200 pages", price: "₹5200", src: "./shirt2.jpg" },
        { name: "Magnetic Desk Toy Kit", price: "₹1200", src: "./cup.jpg" },
        { name: "Enamel Pin, Maxwell's Equations", price: "₹1680", src: "./bag.jpg" },
        { name: "MF Hoodie, Limited Edition", price: "₹1770", src: "./shirt3.jpg" },
    ];

    return (
        <div className="px-3 pt-6 pb-2">
            <div className="grid grid-cols-2 gap-x-3 gap-y-6">
                {items.map(item =>
                    <ShopCard key={item.name} {...item} />
                )}
            </div>
        </div>
    );
}