type Post = {
    type: "post",
    id: string,
    avatar: string,
    name: string,
    date: string,
    body: string,
    likes: string,
    dislikes: string,
    comments: string,
    imgSrc?: string,
}

export const posts: Post[] = [
    {
        type: "post",
        id: "v1",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "2 days ago",
        body: "Just finished filming a 3-part series on the hidden geometry of magnetic field lines. It genuinely blew my mind editing this — dropping next week.",
        likes: "2.4K",
        dislikes: "24",
        comments: "183",
        imgSrc: "./moon.webp",
    },
    {
        type: "post",
        id: "v2",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "1 week ago",
        body: "Hot take: most people fundamentally misunderstand what electricity actually is. It's not electrons flowing like water in a pipe. Thread incoming.",
        likes: "5.1K",
        dislikes: "24",
        comments: "412",
    },
    {
        type: "post",
        id: "v3",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "2 weeks ago",
        body: "Behind the scenes from the Tesla coil build. Three failed prototypes, one minor burn, and a lot of lessons learned. Worth it.",
        likes: "3.8K",
        dislikes: "24",
        comments: "256",
        imgSrc: "./pink.webp",
    },
    {
        type: "post",
        id: "v4",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "2 weeks ago",
        body: "Behind the scenes from the Tesla coil build. Three failed prototypes, one minor burn, and a lot of lessons learned. Worth it.",
        likes: "3.8K",
        dislikes: "24",
        comments: "256",
    },
    {
        type: "post",
        id: "v5",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "2 weeks ago",
        body: "Behind the scenes from the Tesla coil build. Three failed prototypes, one minor burn, and a lot of lessons learned. Worth it.",
        likes: "3.8K",
        dislikes: "24",
        comments: "256",
    },
    {
        type: "post",
        id: "v6",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "2 weeks ago",
        body: "Behind the scenes from the Tesla coil build. Three failed prototypes, one minor burn, and a lot of lessons learned. Worth it.",
        likes: "3.8K",
        dislikes: "24",
        comments: "256",
        imgSrc: "./yellow.webp",
    },
    // Adding 14 more to make it 20 items:
    {
        type: "post",
        id: "v7",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "3 weeks ago",
        body: "Quick update: The community Q&A video is fully recorded. Answering all your burning questions about electromagnetism and early lab days. Stay tuned!",
        likes: "1.7K",
        dislikes: "12",
        comments: "98",
    },
    {
        type: "post",
        id: "v8",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "3 weeks ago",
        body: "We just crossed another milestone on the channel. Thank you all for supporting educational content! I honestly didn't think this many people cared about physics.",
        likes: "6.3K",
        dislikes: "15",
        comments: "320",
        imgSrc: "./japan.jpg",
    },
    {
        type: "post",
        id: "v9",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "1 month ago",
        body: "Spent the whole morning setting up new grounding straps in the laboratory studio. Static charges have been ruining my microphone audio output completely.",
        likes: "2.1K",
        dislikes: "32",
        comments: "114",
    },
    {
        type: "post",
        id: "v10",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "1 month ago",
        body: "Working on a collaborative script with a special guest creator. We're breaking down the physics of why lightning loops the way it does.",
        likes: "4.2K",
        dislikes: "19",
        comments: "280",
        imgSrc: "./painting.jpg",
    },
    {
        type: "post",
        id: "v11",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "1 month ago",
        body: "Do you prefer the deep-dive historical text explanations on these community updates, or should I stick purely to quick video trailers here?",
        likes: "1.9K",
        dislikes: "8",
        comments: "410",
    },
    {
        type: "post",
        id: "v12",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "2 months ago",
        body: "Currently cleaning out the equipment closet. Found five completely burnt copper coils from our induction experiment marathon last autumn. Good times.",
        likes: "3.0K",
        dislikes: "21",
        comments: "167",
        imgSrc: "./thumbnail1.webp",
    },
    {
        type: "post",
        id: "v13",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "2 months ago",
        body: "The upcoming lecture series at the Royal Institution is officially sold out! Looking forward to meeting all of you who managed to grab a pass.",
        likes: "5.5K",
        dislikes: "11",
        comments: "294",
    },
    {
        type: "post",
        id: "v14",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "2 months ago",
        body: "Fun fact: Did you know space is technically a perfect dielectric insulator? Energy transfer mechanics change drastically when you leave the atmosphere.",
        likes: "7.1K",
        dislikes: "48",
        comments: "530",
    },
    {
        type: "post",
        id: "v15",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "2 months ago",
        body: "Taking a short workshop break this weekend to clear my head and organize the presentation notes. Back to full-scale build uploads next week!",
        likes: "2.8K",
        dislikes: "14",
        comments: "85",
        imgSrc: "./moon.webp",
    },
    {
        type: "post",
        id: "v16",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "3 months ago",
        body: "Ran a quick test using high-frequency glass tubes yesterday. The atmospheric glow under vacuum pressure is absolutely magnificent.",
        likes: "4.6K",
        dislikes: "22",
        comments: "215",
    },
    {
        type: "post",
        id: "v17",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "3 months ago",
        body: "A lot of comments on the last video asked about the wire gauge used for the secondary transformers. It was standard 22 AWG heavy magnet wire.",
        likes: "3.4K",
        dislikes: "17",
        comments: "144",
        imgSrc: "./pink.webp",
    },
    {
        type: "post",
        id: "v18",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "3 months ago",
        body: "Next build project involves high-ratio mechanical gear assemblies. Stepping away from electric circuits for just one episode to talk pure kinetic force.",
        likes: "3.9K",
        dislikes: "29",
        comments: "192",
    },
    {
        type: "post",
        id: "v19",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "4 months ago",
        body: "Finally sorted out the audio clipping issues on the workshop mixer. Turns out the isolation transformer casing was completely ungrounded this whole time.",
        likes: "2.3K",
        dislikes: "9",
        comments: "76",
        imgSrc: "./yellow.webp",
    },
    {
        type: "post",
        id: "v20",
        avatar: "./avatar1.webp",
        name: "Michael Faraday",
        date: "4 months ago",
        body: "Drafting the blueprints for a continuous-wave generator setup. The math behind the resonant inductive couplings is turning into quite a headache.",
        likes: "4.9K",
        dislikes: "33",
        comments: "318",
    }
];