type Short = {
    type: "short",
    id: `short-${number}`,
    isMusical: boolean,
    title: string,
    channel: string,
    profilePictureURL: string,
    views: string,
    uploadDate: string,
    thumbnailURL: string,
    duration: string,
};

export const shorts: Short[] = [
    {
        type: "short",
        id: "short-1",
        isMusical: false,
        title: "Japan's Most Beautiful Restaurant 🍃",
        channel: "TravelBites",
        profilePictureURL: "./travel-avatar.webp",
        views: "450K",
        uploadDate: "2 hours ago",
        thumbnailURL: "./japan.jpg",
        duration: "0:45"
    },
    {
        type: "short",
        id: "short-2",
        isMusical: false,
        title: "A rich red bean paste and butter honey toast that gives you maximum guilty pleasure 🍞🧈",
        channel: "TastyBites",
        profilePictureURL: "./food-avatar.webp",
        views: "1.2M",
        uploadDate: "5 hours ago",
        thumbnailURL: "./pink.webp",
        duration: "0:58"
    },
    {
        type: "short",
        id: "short-3",
        isMusical: false,
        title: "SUBLIMAL MSG",
        channel: "ArtTheory",
        profilePictureURL: "./art-avatar.webp",
        views: "89K",
        uploadDate: "1 day ago",
        thumbnailURL: "./painting.jpg",
        duration: "0:15"
    },
    {
        type: "short",
        id: "short-4",
        isMusical: false,
        title: "When the coffee kicks in right before the 9 AM meeting ☕🔥",
        channel: "DevHumor",
        profilePictureURL: "./diy-avatar.webp",
        views: "320K",
        uploadDate: "3 days ago",
        thumbnailURL: "./coffee-short.webp",
        duration: "0:23"
    },
    {
        type: "short",
        id: "short-5",
        isMusical: false,
        title: "POV: You forgot to git commit before formatting your PC 💀",
        channel: "SyntaxError",
        profilePictureURL: "./tech-avatar.webp",
        views: "940K",
        uploadDate: "4 days ago",
        thumbnailURL: "./dev-panic.webp",
        duration: "0:41"
    },
    {
        type: "short",
        id: "short-6",
        isMusical: false,
        title: "Testing the world's strongest magnetic slime! 🧲",
        channel: "What If",
        profilePictureURL: "./whatif-avatar.webp",
        views: "2.1M",
        uploadDate: "1 week ago",
        thumbnailURL: "./slime.webp",
        duration: "0:50"
    },
    {
        type: "short",
        id: "short-7",
        isMusical: false,
        title: "The hidden paradise beach you didn't know existed in Europe 🌴",
        channel: "Drew Binsky",
        profilePictureURL: "./travel-avatar.webp",
        views: "150K",
        uploadDate: "2 weeks ago",
        thumbnailURL: "./beach.webp",
        duration: "0:35"
    },
    {
        type: "short",
        id: "short-8",
        isMusical: false,
        title: "How to perfectly slice an onion like a professional chef 🧅",
        channel: "Joshua Weissman",
        profilePictureURL: "./josh-avatar.webp",
        views: "3.4M",
        uploadDate: "3 days ago",
        thumbnailURL: "./onion.webp",
        duration: "0:59"
    },
    {
        type: "short",
        id: "short-9",
        isMusical: true,
        title: "This keyboard sound test will cure your insomnia 💤",
        channel: "MechKeys",
        profilePictureURL: "./diy-avatar.webp",
        views: "580K",
        uploadDate: "1 month ago",
        thumbnailURL: "./keyboard-asmr.webp",
        duration: "0:45"
    },
    {
        type: "short",
        id: "short-10",
        isMusical: false,
        title: "Unboxing the rarest mechanical watch in the world ⌚✨",
        channel: "Marques Brownlee",
        profilePictureURL: "./tech-avatar.webp",
        views: "1.7M",
        uploadDate: "6 days ago",
        thumbnailURL: "./watch.webp",
        duration: "0:52"
    },
    {
        type: "short",
        id: "short-11",
        isMusical: false,
        title: "Satisfying 3D printing timelapse: Iron Man Helmet 🤖",
        channel: "DIY Creators",
        profilePictureURL: "./diy-avatar.webp",
        views: "4.2M",
        uploadDate: "12 hours ago",
        thumbnailURL: "./printer.webp",
        duration: "0:30"
    },
    {
        type: "short",
        id: "short-12",
        isMusical: false,
        title: "I asked an AI to design a modern apartment and built it 🏢",
        channel: "Linus Tech Tips",
        profilePictureURL: "./linus-avatar.webp",
        views: "810K",
        uploadDate: "2 days ago",
        thumbnailURL: "./apartment.webp",
        duration: "0:55"
    },
    {
        type: "short",
        id: "short-13",
        isMusical: false,
        title: "Fixing a broken iPhone screen in under 60 seconds 📱",
        channel: "TechQuickie",
        profilePictureURL: "./tq-avatar.webp",
        views: "290K",
        uploadDate: "1 week ago",
        thumbnailURL: "./repair.webp",
        duration: "0:59"
    },
    {
        type: "short",
        id: "short-14",
        isMusical: false,
        title: "Dogs reacting to the 'fake walk' trick is pure gold 🐕😂",
        channel: "Tucker Budzyn",
        profilePictureURL: "./dog-avatar.webp",
        views: "5.6M",
        uploadDate: "5 days ago",
        thumbnailURL: "./dog-reaction.webp",
        duration: "0:14"
    },
    {
        type: "short",
        id: "short-15",
        isMusical: false,
        title: "The easiest 3-ingredient dessert you can make tonight 🍫",
        channel: "Gordon Ramsay",
        profilePictureURL: "./gordon-avatar.webp",
        views: "1.1M",
        uploadDate: "3 weeks ago",
        thumbnailURL: "./dessert.webp",
        duration: "0:40"
    },
    {
        type: "short",
        id: "short-16",
        isMusical: false,
        title: "Street food vendor setup speedrun in Bangkok 🍜",
        channel: "TravelBites",
        profilePictureURL: "./travel-avatar.webp",
        views: "730K",
        uploadDate: "2 months ago",
        thumbnailURL: "./bangkok.webp",
        duration: "0:28"
    },
    {
        type: "short",
        id: "short-17",
        isMusical: false,
        title: "What happens when you drop a bouncy ball from a skyscraper? 🔴",
        channel: "Veritasium",
        profilePictureURL: "./veri-avatar.webp",
        views: "8.9M",
        uploadDate: "1 month ago",
        thumbnailURL: "./drop-test.webp",
        duration: "0:47"
    },
    {
        type: "short",
        id: "short-18",
        isMusical: false,
        title: "The secret iOS feature you aren't using daily!",
        channel: "Marques Brownlee",
        profilePictureURL: "./tech-avatar.webp",
        views: "1.3M",
        uploadDate: "Yesterday",
        thumbnailURL: "./iphone-hacks.webp",
        duration: "0:39"
    },
    {
        type: "short",
        id: "short-19",
        isMusical: true,
        title: "This perspective drawing trick is mind-blowing ✏️🏃",
        channel: "Lofi Girl",
        profilePictureURL: "./lofi-avatar.webp",
        views: "240K",
        uploadDate: "3 weeks ago",
        thumbnailURL: "./art-trick.webp",
        duration: "0:51"
    },
    {
        type: "short",
        id: "short-20",
        isMusical: false,
        title: "Can you solve this riddle in 15 seconds? 🧠🧩",
        channel: "Kurzgesagt – In a Nutshell",
        profilePictureURL: "./kurz-avatar.webp",
        views: "1.9M",
        uploadDate: "6 days ago",
        thumbnailURL: "./riddle.webp",
        duration: "0:15"
    }
];