type Video = {
    type: "video",
    id:`video-${number}`,
    isMusical: boolean,
    title: string,
    channel: string,
    profilePictureURL: string,
    views: string,
    uploadDate: string,
    thumbnailURL: string,
    duration: string,
};

export const videos: Video[] = [
    {
        type: "video",
        id: "video-1",
        isMusical: false,
        title: "How I Animate In Desmos Graphing Calculator",
        channel: "CodingHunger",
        profilePictureURL: "./avatar1.webp",
        views: "12K",
        uploadDate: "1 year ago",
        thumbnailURL: "./thumbnail1.webp",
        duration: "9:38"
    },
    {
        type: "video",
        id: "video-2",
        isMusical: false,
        title: "I Bought The Cheapest Electric Car on the Internet",
        channel: "Marques Brownlee",
        profilePictureURL: "./tech-avatar.webp",
        views: "2.4M",
        uploadDate: "3 days ago",
        thumbnailURL: "./car-thumb.webp",
        duration: "14:20"
    },
    {
        type: "video",
        id: "video-3",
        isMusical: false,
        title: "Can This 3-Star Michelin Chef Fix My Horrible Cooking?",
        channel: "Gordon Ramsay",
        profilePictureURL: "./gordon-avatar.webp",
        views: "890K",
        uploadDate: "2 weeks ago",
        thumbnailURL: "./cooking-thumb.webp",
        duration: "22:15"
    },
    {
        type: "video",
        id: "video-4",
        isMusical: false,
        title: "Minecraft, But Every Minute The World Shrinks",
        channel: "MrBeast Gaming",
        profilePictureURL: "./beast-avatar.webp",
        views: "15M",
        uploadDate: "5 days ago",
        thumbnailURL: "./minecraft-thumb.webp",
        duration: "11:45"
    },
    {
        type: "video",
        id: "video-5",
        isMusical: false,
        title: "I Spent 30 Days in Japan's Most Expensive Capsule Hotel",
        channel: "Drew Binsky",
        profilePictureURL: "./travel-avatar.webp",
        views: "1.1M",
        uploadDate: "1 month ago",
        thumbnailURL: "./hotel-thumb.webp",
        duration: "18:02"
    },
    {
        type: "video",
        id: "video-6",
        isMusical: false,
        title: "Why Space Elevators Are Technically Impossible (For Now)",
        channel: "Kurzgesagt – In a Nutshell",
        profilePictureURL: "./kurz-avatar.webp",
        views: "4.5M",
        uploadDate: "Yesterday",
        thumbnailURL: "./space-thumb.webp",
        duration: "8:50"
    },
    {
        type: "video",
        id: "video-7",
        isMusical: true, 
        title: "LO-FI Beats for Studying / Relaxing ☕ (Chill Mix)",
        channel: "Lofi Girl",
        profilePictureURL: "./lofi-avatar.webp",
        views: "23M",
        uploadDate: "3 weeks ago",
        thumbnailURL: "./lofi-thumb.webp",
        duration: "31:10"
    },
    {
        type: "video",
        id: "video-8",
        isMusical: false,
        title: "Is This $100 Used Laptop Actually Good for Gaming?",
        channel: "Linus Tech Tips",
        profilePictureURL: "./linus-avatar.webp",
        views: "720K",
        uploadDate: "6 days ago",
        thumbnailURL: "./laptop-thumb.webp",
        duration: "15:40"
    },
    {
        type: "video",
        id: "video-9",
        isMusical: false,
        title: "How Earth Would Look If the Dinosaurs Never Went Extinct",
        channel: "What If",
        profilePictureURL: "./whatif-avatar.webp",
        views: "310K",
        uploadDate: "2 months ago",
        thumbnailURL: "./dino-thumb.webp",
        duration: "25:12"
    },
    {
        type: "video",
        id: "video-10",
        isMusical: false,
        title: "Building a Hidden Underground Gaming Setup from Scratch",
        channel: "DIY Creators",
        profilePictureURL: "./diy-avatar.webp",
        views: "1.8M",
        uploadDate: "12 hours ago",
        thumbnailURL: "./room-thumb.webp",
        duration: "10:05"
    },
    {
        type: "video",
        id: "video-11",
        isMusical: false,
        title: "The Ultimate 15-Minute Homemade Ramen Recipe",
        channel: "Joshua Weissman",
        profilePictureURL: "./josh-avatar.webp",
        views: "520K",
        uploadDate: "3 months ago",
        thumbnailURL: "./ramen-thumb.webp",
        duration: "13:22"
    },
    {
        type: "video",
        id: "video-12",
        isMusical: false,
        title: "GTA 6 Map Leak: Everything We Know So Far",
        channel: "IGN",
        profilePictureURL: "./ign-avatar.webp",
        views: "3.4M",
        uploadDate: "4 days ago",
        thumbnailURL: "./gta-thumb.webp",
        duration: "6:14"
    },
    {
        type: "video",
        id: "video-13",
        isMusical: false,
        title: "I Left My Dog in a Luxury Pet Hotel for 48 Hours",
        channel: "Tucker Budzyn",
        profilePictureURL: "./dog-avatar.webp",
        views: "890K",
        uploadDate: "6 months ago",
        thumbnailURL: "./dog-thumb.webp",
        duration: "10:30"
    },
    {
        type: "video",
        id: "video-14",
        isMusical: false,
        title: "Every Single Easter Egg in the Marvel Universe Explained",
        channel: "New Rockstars",
        profilePictureURL: "./marvel-avatar.webp",
        views: "415K",
        uploadDate: "2 weeks ago",
        thumbnailURL: "./marvel-thumb.webp",
        duration: "22:40"
    },
    {
        type: "video",
        id: "video-15",
        isMusical: false,
        title: "The Physics of Why Ripped Jeans Are So Hard to Make",
        channel: "Veritasium",
        profilePictureURL: "./veri-avatar.webp",
        views: "1.4M",
        uploadDate: "1 month ago",
        thumbnailURL: "./jeans-thumb.webp",
        duration: "19:15"
    },
    {
        type: "video",
        id: "video-16",
        isMusical: false,
        title: "Speedrunner Beats Elden Ring Blindfolded in Under 1 Hour",
        channel: "Esoterickk",
        profilePictureURL: "./elden-avatar.webp",
        views: "610K",
        uploadDate: "2 months ago",
        thumbnailURL: "./elden-thumb.webp",
        duration: "21:03"
    },
    {
        type: "video",
        id: "video-17",
        isMusical: false,
        title: "I Tried Sleeping 8 Hours a Day For a Week (Shocking Results)",
        channel: "Matt D'Avella",
        profilePictureURL: "./matt-avatar.webp",
        views: "2.8M",
        uploadDate: "5 days ago",
        thumbnailURL: "./sleep-thumb.webp",
        duration: "10:55"
    },
    {
        type: "video",
        id: "video-18",
        isMusical: false,
        title: "10 Simple Keyboard Shortcuts You Aren't Using",
        channel: "TechQuickie",
        profilePictureURL: "./tq-avatar.webp",
        views: "300K",
        uploadDate: "10 hours ago",
        thumbnailURL: "./shortcuts-thumb.webp",
        duration: "7:22"
    },
    {
        type: "video",
        id: "video-19",
        isMusical: true,
        title: "Interstellar Theme Song - Epic Orchestral Cover",
        channel: "Hans Zimmer Live",
        profilePictureURL: "./hans-avatar.webp",
        views: "5.1M",
        uploadDate: "5 months ago",
        thumbnailURL: "./interstellar-thumb.webp",
        duration: "6:45"
    },
    {
        type: "video",
        id: "video-20",
        isMusical: false,
        title: "I Built a Full Mechanical Keyboard Out of LEGO Bricks",
        channel: "MKBHD",
        profilePictureURL: "./tech-avatar.webp",
        views: "950K",
        uploadDate: "1 week ago",
        thumbnailURL: "./lego-thumb.webp",
        duration: "16:18"
    }
];