type Video = {
    type: "video",
    id: `video-${number}`,
    isMusical: boolean,
    title: string,
    channel: string,
    profilePictureURL: string,
    views: string,
    uploadDate: string,
    thumbnailURL: string,
    duration: string,
};

export const videos: Video[] = [
    {
        type: "video",
        id: "video-1",
        isMusical: false,
        title: "How I Animate In Graphing Software",
        channel: "CodeCraft",
        profilePictureURL: "./avatars/developer-minimal.jpg",
        views: "12K",
        uploadDate: "1 year ago",
        thumbnailURL: "./thumbnails/cute-cats.webp",
        duration: "9:38"
    },
    {
        type: "video",
        id: "video-2",
        isMusical: false,
        title: "I Bought The Cheapest Electric Car on the Internet",
        channel: "TechOverhaul",
        profilePictureURL: "./avatars/tech-creator.jpg",
        views: "2.4M",
        uploadDate: "3 days ago",
        thumbnailURL: "./car-thumb.jpg",
        duration: "14:20"
    },
    {
        type: "video",
        id: "video-3",
        isMusical: false,
        title: "Can This Master Chef Fix My Horrible Cooking?",
        channel: "Gourmet Kitchen",
        profilePictureURL: "./avatars/chef.jpg",
        views: "890K",
        uploadDate: "2 weeks ago",
        thumbnailURL: "./cooking-thumb.jpg",
        duration: "22:15"
    },
    {
        type: "video",
        id: "video-4",
        isMusical: false,
        title: "Voxel Survival, But Every Minute The World Shrinks",
        channel: "Pixel Palace",
        profilePictureURL: "./avatars/gamer.jpg",
        views: "15M",
        uploadDate: "5 days ago",
        thumbnailURL: "./minecraft-thumb.jpg",
        duration: "11:45"
    },
    {
        type: "video",
        id: "video-5",
        isMusical: false,
        title: "I Spent 30 Days in a Micro Hotel in Tokyo",
        channel: "Global Wanderer",
        profilePictureURL: "./avatars/traveler.jpg",
        views: "1.1M",
        uploadDate: "1 month ago",
        thumbnailURL: "./hotel-thumb.jpg",
        duration: "18:02"
    },
    {
        type: "video",
        id: "video-6",
        isMusical: false,
        title: "Why Space Elevators Are Technically Impossible (For Now)",
        channel: "CosmoBytes",
        profilePictureURL: "./avatars/astronaut.jpg",
        views: "4.5M",
        uploadDate: "Yesterday",
        thumbnailURL: "./space-thumb.jpg",
        duration: "8:50"
    },
    {
        type: "video",
        id: "video-7",
        isMusical: true,
        title: "LO-FI Beats for Studying / Relaxing ☕ (Chill Mix)",
        channel: "Study Beats Central",
        profilePictureURL: "./avatars/feet.jpg",
        views: "23M",
        uploadDate: "3 weeks ago",
        thumbnailURL: "./lofi-thumb.jpg",
        duration: "31:10"
    },
    {
        type: "video",
        id: "video-8",
        isMusical: false,
        title: "Is This $100 Used Laptop Actually Good for Gaming?",
        channel: "Hardware Haven",
        profilePictureURL: "./avatars/logo.jpg",
        views: "720K",
        uploadDate: "6 days ago",
        thumbnailURL: "./laptop-thumb.jpg",
        duration: "15:40"
    },
    {
        type: "video",
        id: "video-9",
        isMusical: false,
        title: "How Earth Would Look If the Dinosaurs Never Went Extinct",
        channel: "Alternate Timelines",
        profilePictureURL: "./avatars/sci-fi.jpg",
        views: "310K",
        uploadDate: "2 months ago",
        thumbnailURL: "./dino-thumb.jpg",
        duration: "25:12"
    },
    {
        type: "video",
        id: "video-10",
        isMusical: false,
        title: "Building a Hidden Underground Gaming Setup from Scratch",
        channel: "Maker Workshop",
        profilePictureURL: "./avatars/woodworker.jpg",
        views: "1.8M",
        uploadDate: "12 hours ago",
        thumbnailURL: "./room-thumb.jpg",
        duration: "10:05"
    },
    {
        type: "video",
        id: "video-11",
        isMusical: false,
        title: "The Ultimate 15-Minute Homemade Ramen Recipe",
        channel: "Culinary Edge",
        profilePictureURL: "./avatars/asian-chef.jpg",
        views: "520K",
        uploadDate: "3 months ago",
        thumbnailURL: "./ramen-thumb.jpg",
        duration: "13:22"
    },
    {
        type: "video",
        id: "video-12",
        isMusical: false,
        title: "Open-World Game Map Leak: Everything We Know So Far",
        channel: "GameZone Central",
        profilePictureURL: "./avatars/headphones.jpg",
        views: "3.4M",
        uploadDate: "4 days ago",
        thumbnailURL: "./gta-thumb.jpg",
        duration: "6:14"
    },
    {
        type: "video",
        id: "video-13",
        isMusical: false,
        title: "I Left My Dog in a Luxury Pet Hotel for 48 Hours",
        channel: "Paws & Tail Stories",
        profilePictureURL: "./avatars/golden-retriever.jpg",
        views: "890K",
        uploadDate: "6 months ago",
        thumbnailURL: "./dog-thumb.jpg",
        duration: "10:30"
    },
    {
        type: "video",
        id: "video-14",
        isMusical: false,
        title: "Every Single Hidden Detail in Sci-Fi Movies Explained",
        channel: "Cine Breakdown",
        profilePictureURL: "./avatars/lights-camera-action.jpg",
        views: "415K",
        uploadDate: "2 weeks ago",
        thumbnailURL: "./marvel-thumb.jpg",
        duration: "22:40"
    },
    {
        type: "video",
        id: "video-15",
        isMusical: false,
        title: "The Science of Why Denim Fabric Is Hard to Recycle",
        channel: "Everyday Physics",
        profilePictureURL: "./avatars/scientist.jpg",
        views: "1.4M",
        uploadDate: "1 month ago",
        thumbnailURL: "./jeans-thumb.jpg",
        duration: "19:15"
    },
    {
        type: "video",
        id: "video-16",
        isMusical: false,
        title: "Speedrunner Beats Action RPG Blindfolded in Under 1 Hour",
        channel: "Pro Speedruns",
        profilePictureURL: "./avatars/esports-player.jpg",
        views: "610K",
        uploadDate: "2 months ago",
        thumbnailURL: "./elden-thumb.jpg",
        duration: "21:03"
    },
    {
        type: "video",
        id: "video-17",
        isMusical: false,
        title: "I Tried Sleeping 8 Hours a Day For a Week (Surprising Results)",
        channel: "Better Habits",
        profilePictureURL: "./avatars/woman-and-cat.jpg",
        views: "2.8M",
        uploadDate: "5 days ago",
        thumbnailURL: "./woman-and-cat.jpg",
        duration: "10:55"
    },
    {
        type: "video",
        id: "video-18",
        isMusical: false,
        title: "10 Simple Keyboard Shortcuts You Aren't Using",
        channel: "Quick Tech Tips",
        profilePictureURL: "./avatars/tech-logo.jpg",
        views: "300K",
        uploadDate: "10 hours ago",
        thumbnailURL: "./tech-logo.jpg",
        duration: "7:22"
    },
    {
        type: "video",
        id: "video-19",
        isMusical: true,
        title: "Deep Space Movie Soundtrack - Epic Orchestral Cover",
        channel: "Symphonic Echoes",
        profilePictureURL: "./avatars/conductor.jpg",
        views: "5.1M",
        uploadDate: "5 months ago",
        thumbnailURL: "./conductor.jpg",
        duration: "6:45"
    },
    {
        type: "video",
        id: "video-20",
        isMusical: false,
        title: "I Built a Full Mechanical Keyboard Out of Toy Bricks",
        channel: "Tech Tinkerer",
        profilePictureURL: "./avatars/lego.jpg",
        views: "950K",
        uploadDate: "1 week ago",
        thumbnailURL: "./lego.jpg",
        duration: "16:18"
    }
];