type Video = {
    type: "video",
    id: `video-${number}`,
    isMusical: boolean,
    title: string,
    channel: string,
    profilePictureURL: string,
    views: string,
    uploadDate: string,
    thumbnailURL: string,
    duration: string,
};

export const videos: Video[] = [
    {
        type: "video",
        id: "video-1",
        isMusical: false,
        title: "How I animate stuff on Desmos Graphing Calculator",
        channel: "Junferno",
        profilePictureURL: "./profilePictures/graphingCalculator.jpg",
        views: "3.5M",
        uploadDate: "5 year ago",
        thumbnailURL: "./thumbnails/graphingCalculator.webp",
        duration: "7:49"
    },
    {
        type: "video",
        id: "video-2",
        isMusical: true,
        title: "Driving Xiaomi's Electric Car: Are we Cooked?",
        channel: "Marques Brownlee",
        profilePictureURL: "./profilePictures/mkbhd.jpg",
        views: "11M",
        uploadDate: "9 months ago",
        thumbnailURL: "./thumbnails/mkbhd.webp",
        duration: "17:25"
    },
    {
        type: "video",
        id: "video-3",
        isMusical: false,
        title: "Dining at the ONLY 3 MICHELIN-STAR Restaurant In Milan",
        channel: "Alexander On The Road",
        profilePictureURL: "./profilePictures/food.jpg",
        views: "40K",
        uploadDate: "21 hours ago",
        thumbnailURL: "./thumbnails/food.webp",
        duration: "33:56"
    },
    {
        type: "video",
        id: "video-4",
        isMusical: false,
        title: "Minecraft, But You Shrink Every Minute...",
        channel: "SB737",
        profilePictureURL: "./profilePictures/sb737.jpg",
        views: "6.7M",
        uploadDate: "3 years ago",
        thumbnailURL: "./thumbnails/sb737.webp",
        duration: "20:21"
    },
    {
        type: "video",
        id: "video-5",
        isMusical: false,
        title: "Jonathan Blow - Jai Demo and Design Explanation (KEYNOTE) Updated",
        channel: "LambdaConf",
        profilePictureURL: "./profilePictures/blow.jpg",
        views: "232K",
        uploadDate: "1 year ago",
        thumbnailURL: "./thumbnails/blow.webp",
        duration: "1:13:00"
    },
    {
        type: "video",
        id: "video-6",
        isMusical: false,
        title: "Space Elevator – Science Fiction or the Future of Mankind?",
        channel: "Kurzgesagt – In a Nutshell",
        profilePictureURL: "./profilePictures/elevator.jpg",
        views: "8.5M",
        uploadDate: "10 years ago",
        thumbnailURL: "./thumbnails/elevator.webp",
        duration: "5:26"
    },
    {
        type: "video",
        id: "video-7",
        isMusical: true, 
        title: "LO-FI Beats for Studying / Relaxing ☕ (Chill Mix)",
        channel: "Lofi Girl",
        profilePictureURL: "./profilePictures/lofi.jpg",
        views: "136M",
        uploadDate: "1 years ago",
        thumbnailURL: "./thumbnails/lofi.webp",
        duration: "1:01:14"
    },
    {
        type: "video",
        id: "video-8",
        isMusical: true,
        title: "Indian man sings unravel full song HD",
        channel: "Paco8478",
        profilePictureURL: "./profilePictures/unravel.jpg",
        views: "1.2M",
        uploadDate: "4 years ago",
        thumbnailURL: "./thumbnails/unravel.webp",
        duration: "4:01"
    },
    {
        type: "video",
        id: "video-9",
        isMusical: false,
        title: "Unique Homemade Burgers! Korean Double Cheeseburger & Steak Sandwich | Korean street food",
        channel: "끼룩푸드 seagull food",
        profilePictureURL: "./profilePictures/kfood.jpg",
        views: "1.2M",
        uploadDate: "2 weeks ago",
        thumbnailURL: "./thumbnails/kfood.webp",
        duration: "23:43"
    },
    {
        type: "video",
        id: "video-10",
        isMusical: false,
        title: "I built a HIDDEN gaming room in my closet",
        channel: "President Chay",
        profilePictureURL: "./profilePictures/gaming.jpg",
        views: "1.8M",
        uploadDate: "2 years ago",
        thumbnailURL: "./thumbnails/gaming.webp",
        duration: "15:12"
    },
    {
        type: "video",
        id: "video-11",
        isMusical: false,
        title: "The last IMO problem AI could not solve",
        channel: "3Blue1Brown",
        profilePictureURL: "./profilePictures/3b1b.jpg",
        views: "2.3M",
        uploadDate: "7 days ago",
        thumbnailURL: "./thumbnails/3b1b.webp",
        duration: "51:56"
    },
    {
        type: "video",
        id: "video-12",
        isMusical: true,
        title: "Sansoon Ki Mala Pe Simron Mein Pee Ka Naam - Ustad Nusrat Fateh Ali Khan - OSA Official HD Video",
        channel: "Oriental Star Agencies Ltd",
        profilePictureURL: "./profilePictures/nushrat.jpg",
        views: "25M",
        uploadDate: "10 years ago",
        thumbnailURL: "./thumbnails/nushrat.webp",
        duration: "24:35"
    },
    {
        type: "video",
        id: "video-13",
        isMusical: false,
        title: "I Left My Dog in a Luxury Pet Hotel for 48 Hours",
        channel: "Tucker Budzyn",
        profilePictureURL: "./profilePictures/dog-avatar.jpg",
        views: "890K",
        uploadDate: "6 months ago",
        thumbnailURL: "./thumbnails/dog-thumb.webp",
        duration: "10:30"
    },
    {
        type: "video",
        id: "video-14",
        isMusical: false,
        title: "Every Single Easter Egg in the Marvel Universe Explained",
        channel: "New Rockstars",
        profilePictureURL: "./profilePictures/marvel-avatar.jpg",
        views: "415K",
        uploadDate: "2 weeks ago",
        thumbnailURL: "./thumbnails/marvel-thumb.webp",
        duration: "22:40"
    },
    {
        type: "video",
        id: "video-15",
        isMusical: false,
        title: "The Physics of Why Ripped Jeans Are So Hard to Make",
        channel: "Veritasium",
        profilePictureURL: "./profilePictures/veri-avatar.jpg",
        views: "1.4M",
        uploadDate: "1 month ago",
        thumbnailURL: "./thumbnails/jeans-thumb.webp",
        duration: "19:15"
    },
    {
        type: "video",
        id: "video-16",
        isMusical: false,
        title: "Speedrunner Beats Elden Ring Blindfolded in Under 1 Hour",
        channel: "Esoterickk",
        profilePictureURL: "./profilePictures/elden-avatar.jpg",
        views: "610K",
        uploadDate: "2 months ago",
        thumbnailURL: "./thumbnails/elden-thumb.webp",
        duration: "21:03"
    },
    {
        type: "video",
        id: "video-17",
        isMusical: false,
        title: "I Tried Sleeping 8 Hours a Day For a Week (Shocking Results)",
        channel: "Matt D'Avella",
        profilePictureURL: "./profilePictures/matt-avatar.jpg",
        views: "2.8M",
        uploadDate: "5 days ago",
        thumbnailURL: "./thumbnails/sleep-thumb.webp",
        duration: "10:55"
    },
    {
        type: "video",
        id: "video-18",
        isMusical: false,
        title: "10 Simple Keyboard Shortcuts You Aren't Using",
        channel: "TechQuickie",
        profilePictureURL: "./profilePictures/tq-avatar.jpg",
        views: "300K",
        uploadDate: "10 hours ago",
        thumbnailURL: "./thumbnails/shortcuts-thumb.webp",
        duration: "7:22"
    },
    {
        type: "video",
        id: "video-19",
        isMusical: true,
        title: "Interstellar Theme Song - Epic Orchestral Cover",
        channel: "Hans Zimmer Live",
        profilePictureURL: "./profilePictures/hans-avatar.jpg",
        views: "5.1M",
        uploadDate: "5 months ago",
        thumbnailURL: "./thumbnails/interstellar-thumb.webp",
        duration: "6:45"
    },
    {
        type: "video",
        id: "video-20",
        isMusical: false,
        title: "I Built a Full Mechanical Keyboard Out of LEGO Bricks",
        channel: "MKBHD",
        profilePictureURL: "./profilePictures/tech-avatar.jpg",
        views: "950K",
        uploadDate: "1 week ago",
        thumbnailURL: "./thumbnails/lego-thumb.webp",
        duration: "16:18"
    }
];